[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    ignore:.*oneOf.*:DeprecationWarning
    ignore:.*parseString.*:DeprecationWarning
    ignore:.*resetCache.*:DeprecationWarning
    ignore:.*enablePackrat.*:DeprecationWarning
